### ISSUE TITLE
An uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by ChandZhang** [baidubce/bce-capture-ios#2]
包里提供的LiveDemo，在运行时正常，但是到推流界面就会抛出如下异常：
LiveDemo[3886:293054] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[VSVideoCamera setMirrorFrontFacingCamera:]: unrecognized selector sent to instance 0x7fe072d12b40'
只是把使用前置摄像头改为了使用后置摄像头。其他任何参数都没有修改过。

**Comment by stayHF** [comment]
因为推流端需要使用到摄像头设备，所以不支持在模拟器上运行。
